---
new_page_extension: md
auto_deploy: true
admin_path: C:\Users\jay khay\Desktop\Jamie
webhook_url: jamiekhay@gmail.com
sections:
- type: directory
  path: C:\Users\jay khay\Desktop\Jamie
  label: Side Out
  create: all
  match: "**/*"
  new_doc_ext: mode.md
  templates:
  - 2-column-media-element
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
- type: jekyll-posts
  label: Posts
  create: documents
  new_doc_ext: MODE
  templates:
  - full-width-media-element
  - hero-banner-w-image
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
  templates:
  - signup-bar
- type: document
  path: _config.yml
  label: Side out
upload_dir: C:\Users\jay khay\Desktop\Jamie
public_path: C:\Users\jay khay\Desktop\Jamie
front_matter_path: C:\Users\jay khay\Desktop\Jamie
use_front_matter_path: true
file_template: 'C:\Users\jay khay\Desktop\Jamie/:filename:'
build:
  preview_env:
  - JEKYLL_ENV=staging
  - JAMIE_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --config _config.yml,_config_staging.yml
    --drafts --unpublished --future --port 8080 --host 0.0.0.0 -d _site
